#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : termcolor
Version  : 1.1.0
Release  : 6
URL      : https://pypi.python.org/packages/source/t/termcolor/termcolor-1.1.0.tar.gz
Source0  : https://pypi.python.org/packages/source/t/termcolor/termcolor-1.1.0.tar.gz
Summary  : ANSII Color formatting for output in terminal.
Group    : Development/Tools
License  : MIT
Requires: termcolor-python
BuildRequires : python-dev
BuildRequires : setuptools

%description
Example
=======
::
import sys
from termcolor import colored, cprint
text = colored('Hello, World!', 'red', attrs=['reverse', 'blink'])
print(text)
cprint('Hello, World!', 'green', 'on_red')

%package python
Summary: python components for the termcolor package.
Group: Default

%description python
python components for the termcolor package.


%prep
%setup -q -n termcolor-1.1.0

%build
%{__python} setup.py build

%install
rm -rf %{buildroot}
%{__python} setup.py install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
